#!/bin/bash
#This script is executed every time your instance is spawned.

sudo chsh -s /usr/bin/zsh htb-crisb
sudo timedatectl set-timezone Europe/Berlin

#install ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#install autosuggester
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

#install syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

wget https://raw.githubusercontent.com/hannibal-smith/scripts/master/omz/kali.zsh.theme -O ~/.oh-my-zsh/themes/kali.zsh-theme

sed -i 's/plugins=(git)/plugins=(git tmux nmap python zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
