#!/bin/bash
#This script is executed every time your instance is spawned.

sudo chsh -s /usr/bin/zsh htb-crisb
sudo timedatectl set-timezone Europe/Berlin

wget https://raw.githubusercontent.com/hannibal-smith/scripts/master/htb-pwn/.tmux.conf -O ~/.tmux.conf

#install ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

#install autosuggester
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

#install syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

wget https://raw.githubusercontent.com/hannibal-smith/scripts/master/omz/kali.zsh.theme -O ~/.oh-my-zsh/themes/kali.zsh-theme

sed -i 's/plugins=(git)/plugins=(git tmux nmap python zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
sed -i 's/robbyrussell/kali/' ~/.zshrc

#gsettings set org.mate.background picture-filename /usr/share/backgrounds/htb.jpg
sudo dconf write /org/mate/desktop/background/picture-filename "'/usr/share/backgrounds/htb.jpg'"

echo "export SHELL=/bin/zsh" >> ~/.bashrc
echo "/bin/zsh -l" >> ~/.bashrc

cd /home/htb-crisb
git clone https://github.com/tmux-plugins/tpm /home/htb-crisb/.tmux/plugins/tpm
mkdir -p /home/htb-crisb/.local/share/fonts
wget https://github.com/adobe-fonts/source-code-pro/raw/release/OTF/SourceCodePro-Medium.otf -O /home/htb-crisb/.local/share/fonts/SourceCodePro-Medium.otf

# refresh font cache
if which fc-cache >/dev/null 2>&1 ; then
    fc-cache -f "$font_dir"
fi

dconf load /org/mate/terminal/profiles/default/ < /home/htb-crisb/my_data/mate-terminal/default.mtconf
